In [7]:
# --------- import required functions

from tensorflow.keras.layers import *
import pandas as pd



from tensorflow.keras.layers import *
from glob import glob
from keras import backend as K
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras.models import Model
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, KFold
from keras.preprocessing.image import ImageDataGenerator
import os
import cv2
import numpy as np
from tensorflow.keras.utils import CustomObjectScope



In [8]:
# -------------dice and dice_loss 
def dice_coef(y_true, y_pred, smooth=1):
    y_true = K.cast(y_true, 'float64')
    y_pred = K.cast(y_pred, 'float64')
    intersection = K.sum(y_true * y_pred, axis=[1,2,3])
    union        = K.sum(y_true, axis=[1,2,3]) + K.sum(y_pred, axis=[1,2,3])
    dice         = K.mean((2. * intersection + smooth)/(union + smooth), axis=0)
    return dice

def dice_loss(y_true, y_pred):
  return 1.-dice_coef(y_true, y_pred)


# ----------build_unet  
class CONV:
    def conv_block(data, base, batchnorm=False):
        # --------------- 1st block
        x = Conv2D(filters=base, kernel_size=(3, 3), padding='same')(data)
        if batchnorm:
            x = BatchNormalization()(x)
        x = Activation("relu")(x)
        # --------------- 2nd block
        x = Conv2D(filters=base, kernel_size=(3, 3), padding='same')(x)
        if batchnorm:
            x = BatchNormalization()(x)
        x = Activation("relu")(x)
        return x

def build_unet(h, w, c, base, classes, dropout=True, batchnorm=True):
    num_filters = [base, base * 2, base * 4, base * 8]
    inputs = Input((h, w, c))

    skip_x = []
    x = inputs

    # ----------------- Encoder
    for f in num_filters:
        x = CONV.conv_block(x, f, batchnorm=True)
        skip_x.append(x)
        x = MaxPooling2D(pool_size=(2, 2), padding="same")(x)
        if dropout:
            x = Dropout(0.2)(x)

            # ----------------- Bridge
    x = CONV.conv_block(x, num_filters[-1], batchnorm=True)
    # x = MaxPooling2D(pool_size=(2, 2), padding="same") (x)  # no need to this layer
    if dropout:
        x = Dropout(0.2)(x)

    num_filters.reverse()
    skip_x.reverse()

    # ----------------- Decoder
    for i, f in enumerate(num_filters):
        #x = UpSampling2D((2, 2))(x)  # Conv2DTranspose(f, (2,2)) (x)
        x = Conv2DTranspose(filters=f, kernel_size=(3, 3), strides=(2, 2), padding='same')(x)
        xs = skip_x[i]
        #height, width = determine_crop(xs, x)
        #crop_xs = Cropping2D(cropping=(height, width))(xs)
        x = Concatenate()([x, xs])
        if dropout:
            x = Dropout(0.2)(x)
        x = CONV.conv_block(x, f, batchnorm=True)

    # ----------------- Output
    out = Conv2D(classes, (1, 1), padding="same", activation='sigmoid')(x)

    # ----------------- input and output
    model = Model(inputs=inputs, outputs=out)
    model.summary()
    return model




In [33]:
modelFilePath = "./"
mainPath="I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset"
workDir = "images"
outDir = "cutOffByMaskOutput"
workPath = os.path.join(mainPath,workDir)
outPath = os.path.join(mainPath,outDir)

In [90]:
model = tf.keras.models.load_model(os.path.join(modelFilePath, 'model.h5'), compile=False)
model.compile() 

In [71]:
def load_data(ipath):
    pattern_ipath = ipath + "/*" 

    images = sorted(glob(os.path.join(pattern_ipath)))

    images = np.array(images)

    indices = np.arange(images.shape[0])
    np.random.shuffle(indices)

    images = images[indices]

    return images.tolist()

def read_image(path, H=912, W=912):
    x = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    x = cv2.resize(x, (W,H))
    x = x/255.0
    x = x.astype(np.float32)
    return x



def preprocess(x,H=912, W=912):

    def f(x):
        print(x)
        x = x.decode()

        x = read_image(x)

        return x

    images = tf.numpy_function(f, [x], [tf.float32])
    #print(images)
       #images.set_shape([H, W, 1])

    return images

AUTOTUNE = tf.data.AUTOTUNE

def tf_data(x):
    data = tf.data.Dataset.from_tensor_slices((x))
    data = data.cache()
    #data = data.shuffle(buffer_size=1000)
    data = data.map(preprocess, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    data = data.batch(1)
    data = data.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
    return data


In [72]:
fileList = load_data(workPath)
dataset_ = tf_data(fileList)
for z in dataset_:
    print(z)

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6114_batch2_white_ok_1.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN6937_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS5906_batch2_white_ok_2.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6272_batch2_white_ok_1.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4778_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6503_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG975_batch2_brown_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1262_batch2_brown_ok_0.jpg'
b'I:\\download\\deepLearn

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.2627451 , 0.24705882, 0.08627451, ..., 0.11372549,
         0.13725491, 0.10980392],
        [0.25882354, 0.2509804 , 0.1254902 , ..., 0.10980392,
         0.14901961, 0.13333334],
        [0.27058825, 0.24705882, 0.09411765, ..., 0.05882353,
         0.10196079, 0.10588235],
        ...,
        [0.2627451 , 0.23921569, 0.09411765, ..., 0.99607843,
         1.        , 1.        ],
        [0.24705882, 0.23137255, 0.07058824, ..., 1.        ,
         1.        , 1.        ],
        [0.24705882, 0.24313726, 0.06666667, ..., 0.8392157 ,
         0.8156863 , 0.77254903]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.29411766, 0.2784314 , 0.17254902, ..., 0.10588235,
         0.04313726, 0.        ],
        [0.25490198, 0.23137255, 0.1254902 , ..., 0.07843138,
         0.04313726, 0.        ],
        [0.25490198, 0.23137255, 0.11764706, ..., 0.07058824,
         0.08235294, 0.02

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.25490198, 0.23529412, 0.08235294, ..., 0.09019608,
         0.14117648, 0.13333334],
        [0.2901961 , 0.27058825, 0.14117648, ..., 0.08627451,
         0.14117648, 0.09411765],
        [0.2784314 , 0.23529412, 0.08627451, ..., 0.07058824,
         0.10980392, 0.09803922],
        ...,
        [0.4509804 , 0.36078432, 0.14117648, ..., 0.23921569,
         0.23921569, 0.14117648],
        [0.43137255, 0.33333334, 0.15294118, ..., 0.15294118,
         0.15686275, 0.11372549],
        [0.4117647 , 0.31764707, 0.17254902, ..., 0.14901961,
         0.14509805, 0.10980392]]], dtype=float32)>,)b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4926_batch2_white_ok_0.jpg'

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.42352942, 0.38039216, 0.24705882, ..., 0.16862746,
         0.16862746, 0.17254902],
        [0.5254902 , 0.47058824, 0.3529412 , ..., 0.2627451 ,

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4582_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG409_batch2_brown_ok_1.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4843_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.25882354, 0.21568628, 0.10196079, ..., 0.09803922,
         0.09803922, 0.01960784],
        [0.23921569, 0.19215687, 0.08235294, ..., 0.07843138,
         0.07843138, 0.02352941],
        [0.23529412, 0.19215687, 0.07058824, ..., 0.10980392,
         0.10980392, 0.07058824],
        ...,
        [0.07843138, 0.07450981, 0.03137255, ..., 0.03529412,
         0.05882353, 0.0627451 ],
        [0.09803922, 0.09019608, 0.04705882, ..., 0.10588235,
         0.14117648, 0.13333334],
        [0.09803922, 0.08235294, 0.02745098, ..., 0.05882353,
         0.11372549, 0.0

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.17254902, 0.14509805, 0.05882353, ..., 0.05098039,
         0.06666667, 0.04313726],
        [0.17254902, 0.14509805, 0.05490196, ..., 0.03921569,
         0.05882353, 0.04705882],
        [0.1882353 , 0.15686275, 0.0627451 , ..., 0.05882353,
         0.07058824, 0.04705882],
        ...,
        [0.06666667, 0.07450981, 0.03529412, ..., 0.05490196,
         0.08235294, 0.05882353],
        [0.11372549, 0.12156863, 0.07843138, ..., 0.09803922,
         0.10980392, 0.09019608],
        [0.11372549, 0.11764706, 0.05882353, ..., 0.05490196,
         0.06666667, 0.02352941]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.29803923, 0.3254902 , 0.17254902, ..., 0.08627451,
         0.16078432, 0.13333334],
        [0.3647059 , 0.3882353 , 0.27450982, ..., 0.18431373,
         0.23921569, 0.21176471],
        [0.3372549 , 0.3137255 , 0.1764706 , ..., 0.15686275,
         0.19215687, 0.19

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4526_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4630_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.2784314 , 0.25882354, 0.11764706, ..., 0.0627451 ,
         0.10196079, 0.11764706],
        [0.27450982, 0.26666668, 0.13725491, ..., 0.12156863,
         0.1764706 , 0.1882353 ],
        [0.2627451 , 0.21176471, 0.07058824, ..., 0.07450981,
         0.12156863, 0.12156863],
        ...,
        [0.34117648, 0.3137255 , 0.10588235, ..., 0.07450981,
         0.07843138, 0.06666667],
        [0.3647059 , 0.32156864, 0.10588235, ..., 0.09803922,
         0.09803922, 0.09803922],
        [0.4117647 , 0.36078432, 0.16862746, ..., 0.07450981,
         0.07843138, 0.05490196]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.28235295, 0.23921569, 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN6265_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4469_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.21568628, 0.19215687, 0.09803922, ..., 0.09803922,
         0.14117648, 0.1254902 ],
        [0.21960784, 0.21176471, 0.09411765, ..., 0.1254902 ,
         0.15294118, 0.14117648],
        [0.19607843, 0.1764706 , 0.06666667, ..., 0.09803922,
         0.09019608, 0.07843138],
        ...,
        [0.24705882, 0.20392157, 0.10588235, ..., 0.92156863,
         0.92156863, 0.8627451 ],
        [0.3137255 , 0.27058825, 0.15294118, ..., 0.5058824 ,
         0.5137255 , 0.49411765],
        [0.3137255 , 0.2509804 , 0.05882353, ..., 0.20392157,
         0.23529412, 0.23529412]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.14901961, 0.15294118, 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6414_batch2_white_ok_0.jpg'b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6182_batch2_white_ok_1.jpg'

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.3529412 , 0.26666668, 0.14117648, ..., 0.0627451 ,
         0.07450981, 0.07843138],
        [0.3372549 , 0.25490198, 0.11764706, ..., 0.07450981,
         0.09411765, 0.09411765],
        [0.3137255 , 0.2509804 , 0.11372549, ..., 0.07450981,
         0.08627451, 0.09019608],
        ...,
        [0.4117647 , 0.33333334, 0.20392157, ..., 0.17254902,
         0.16470589, 0.12156863],
        [0.41568628, 0.34509805, 0.22745098, ..., 0.2       ,
         0.19607843, 0.16078432],
        [0.30588236, 0.24313726, 0.15686275, ..., 0.14901961,
         0.15294118, 0.12941177]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.25490198, 0.2509804 , 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6005_batch2_white_ok_1.jpg'(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.        , 0.        , 0.        , ..., 0.14117648,
         0.13725491, 0.07058824],
        [0.        , 0.        , 0.        , ..., 0.09803922,
         0.10196079, 0.08235294],
        [0.        , 0.        , 0.        , ..., 0.11372549,
         0.09803922, 0.03921569],
        ...,
        [0.24313726, 0.21176471, 0.10980392, ..., 0.09411765,
         0.11764706, 0.09803922],
        [0.29803923, 0.27058825, 0.14117648, ..., 0.12156863,
         0.17254902, 0.1764706 ],
        [0.27450982, 0.24313726, 0.09019608, ..., 0.08235294,
         0.14901961, 0.13333334]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4478_batch2_white_ok_0.jpg'

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_0202

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG934_batch2_brown_ok_1.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4444_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN5930_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.34901962, 0.4       , 0.3647059 , ..., 0.32156864,
         0.3882353 , 0.36862746],
        [0.60784316, 0.6156863 , 0.5294118 , ..., 0.40784314,
         0.5019608 , 0.45882353],
        [0.627451  , 0.5882353 , 0.48235294, ..., 0.33333334,
         0.4117647 , 0.40784314],
        ...,
        [0.92941177, 0.93333334, 0.9411765 , ..., 0.23921569,
         0.19215687, 0.08627451],
        [1.        , 0.99607843, 1.        , ..., 0.21960784,
         0.21568628, 0.21176471],
        [0.9843137 , 1.        , 0.99607843, ..., 0.16078432,
         0.15686275, 0.1

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4803_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.40784314, 0.34117648, 0.1764706 , ..., 0.21176471,
         0.2509804 , 0.24313726],
        [0.42352942, 0.3764706 , 0.25490198, ..., 0.22745098,
         0.2627451 , 0.24705882],
        [0.41568628, 0.34509805, 0.21176471, ..., 0.20392157,
         0.22352941, 0.13725491],
        ...,
        [0.99607843, 0.96862745, 0.9411765 , ..., 0.1254902 ,
         0.1254902 , 0.05490196],
        [1.        , 0.99607843, 0.99607843, ..., 0.1254902 ,
         0.11372549, 0.01960784],
        [1.        , 0.98039216, 0.96862745, ..., 0.09411765,
         0.09411765, 0.01960784]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4483_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.23137255, 0.21176471, 0.

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.40784314, 0.32941177, 0.16078432, ..., 0.25882354,
         0.30588236, 0.3372549 ],
        [0.4392157 , 0.38039216, 0.24705882, ..., 0.36078432,
         0.4392157 , 0.48235294],
        [0.3882353 , 0.32156864, 0.1882353 , ..., 0.27058825,
         0.34509805, 0.34117648],
        ...,
        [0.03529412, 0.03137255, 0.16470589, ..., 0.19607843,
         0.22745098, 0.21568628],
        [0.02745098, 0.03529412, 0.19607843, ..., 0.34901962,
         0.34117648, 0.1882353 ],
        [0.02745098, 0.03921569, 0.21176471, ..., 0.33333334,
         0.34117648, 0.3019608 ]]], dtype=float32)>,)b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN5077_batch2_white_ok_0.jpg'

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4384_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.25490198, 0.21568628, 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1699_batch2_brown_ok_1.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.44705883, 0.40392157, 0.23529412, ..., 0.22745098,
         0.21960784, 0.2       ],
        [0.47058824, 0.43529412, 0.28627452, ..., 0.36862746,
         0.36078432, 0.3019608 ],
        [0.46666667, 0.40784314, 0.3137255 , ..., 0.28235295,
         0.28235295, 0.27450982],
        ...,
        [0.20392157, 0.21568628, 0.12941177, ..., 0.11764706,
         0.1254902 , 0.1254902 ],
        [0.1882353 , 0.22352941, 0.10980392, ..., 0.11764706,
         0.11764706, 0.09411765],
        [0.16862746, 0.20392157, 0.09411765, ..., 0.11372549,
         0.1254902 , 0.12941177]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6381_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_0202

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4424_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN6259_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.05882353, 0.04313726, 0.        , ..., 0.09411765,
         0.09411765, 0.03529412],
        [0.05490196, 0.04313726, 0.        , ..., 0.10980392,
         0.10588235, 0.05490196],
        [0.08627451, 0.06666667, 0.01568628, ..., 0.09019608,
         0.09019608, 0.03921569],
        ...,
        [0.3254902 , 0.27058825, 0.17254902, ..., 0.11764706,
         0.1882353 , 0.19607843],
        [0.31764707, 0.28235295, 0.19607843, ..., 0.16078432,
         0.24705882, 0.26666668],
        [0.3372549 , 0.28627452, 0.09803922, ..., 0.11372549,
         0.1764706 , 0.2       ]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.23529412, 0.21960784, 0.

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.2509804 , 0.30980393, 0.15294118, ..., 0.07450981,
         0.14117648, 0.13725491],
        [0.2784314 , 0.34117648, 0.23137255, ..., 0.11764706,
         0.18431373, 0.18431373],
        [0.3019608 , 0.27450982, 0.17254902, ..., 0.07843138,
         0.13725491, 0.12941177],
        ...,
        [0.45490196, 0.3764706 , 0.21960784, ..., 0.05882353,
         0.0627451 , 0.01176471],
        [0.3019608 , 0.22352941, 0.13333334, ..., 0.05882353,
         0.05490196, 0.        ],
        [0.29411766, 0.21568628, 0.09803922, ..., 0.03137255,
         0.02745098, 0.        ]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6653_batch2_white_ok_1.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG425_batch2_brown_ok_3.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4829_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.17254902, 0.16078432, 0.03529412, ..., 0.05490196,
         0.05490196, 0.03137255],
        [0.1764706 , 0.1764706 , 0.05490196, ..., 0.07843138,
         0.07843138, 0.05882353],
        [0.2       , 0.19607843, 0.07843138, ..., 0.05882353,
         0.05882353, 0.03921569],
        ...,
        [0.23137255, 0.19607843, 0.06666667, ..., 0.0627451 ,
         0.10588235, 0.11372549],
        [0.21568628, 0.1882353 , 0.05490196, ..., 0.09411765,
         0.12941177, 0.12941177],
        [0.13333334, 0.13333334, 0.03137255, ..., 0.10980392,
         0.11372549, 0.06666667]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.3647059 , 0.31764707, 0.19215687, ..., 0.22352941,
         0.2509804 , 0.23921569],
        [0.41960785, 0.3764706 , 0.3137255 , ..., 0.30588236,

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG944_batch2_brown_ok_1.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN6233_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.14901961, 0.17254902, 0.06666667, ..., 0.08235294,
         0.14509805, 0.15686275],
        [0.21176471, 0.19215687, 0.0627451 , ..., 0.05882353,
         0.12941177, 0.14509805],
        [0.22745098, 0.1882353 , 0.07450981, ..., 0.0627451 ,
         0.09803922, 0.09803922],
        ...,
        [0.18431373, 0.18431373, 0.14509805, ..., 0.11372549,
         0.1254902 , 0.12156863],
        [0.19607843, 0.20784314, 0.1254902 , ..., 0.10588235,
         0.11372549, 0.09803922],
        [0.20392157, 0.20392157, 0.08627451, ..., 0.14117648,
         0.11764706, 0.06666667]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.32941177, 0.27058825, 0.2

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6250_batch2_white_ok_1.jpg'b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1882_batch2_brown_ok_0.jpg'

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.3529412 , 0.28627452, 0.14901961, ..., 0.11372549,
         0.10980392, 0.07058824],
        [0.3137255 , 0.2509804 , 0.11764706, ..., 0.09411765,
         0.09019608, 0.05882353],
        [0.32941177, 0.2627451 , 0.1254902 , ..., 0.07843138,
         0.07843138, 0.07843138],
        ...,
        [0.5568628 , 0.4862745 , 0.4509804 , ..., 0.14901961,
         0.14509805, 0.1254902 ],
        [0.6784314 , 0.5803922 , 0.45490196, ..., 0.23529412,
         0.23921569, 0.21176471],
        [0.6392157 , 0.53333336, 0.33333334, ..., 0.21176471,
         0.21176471, 0.15294118]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.26666668, 0.22352941, 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG487_batch2_brown_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN5796_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.3137255 , 0.3137255 , 0.13725491, ..., 0.10980392,
         0.1764706 , 0.18039216],
        [0.3372549 , 0.34117648, 0.18039216, ..., 0.14901961,
         0.21568628, 0.20784314],
        [0.32941177, 0.2901961 , 0.14117648, ..., 0.09803922,
         0.14117648, 0.13725491],
        ...,
        [0.99607843, 1.        , 0.99607843, ..., 0.16862746,
         0.21568628, 0.19607843],
        [1.        , 1.        , 0.99215686, ..., 0.16470589,
         0.22745098, 0.22745098],
        [0.9843137 , 0.9607843 , 0.91764706, ..., 0.21176471,
         0.23529412, 0.21176471]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.22745098, 0.23137255, 0.11764706, ..., 0.00392157,
         0.01176471, 0.01960784],
        [0.19215687, 0.19215687, 0.08235294, ..., 0.00392157,
         0.01176471, 0.01960784],
        [0.20784314, 0.2       , 0.07843138, ..., 0.02745098,
         0.02745098, 0.01960784],
        ...,
        [0.83137256, 0.72156864, 0.46666667, ..., 0.45490196,
         0.54509807, 0.5529412 ],
        [0.75686276, 0.6313726 , 0.42745098, ..., 0.4627451 ,
         0.49411765, 0.43529412],
        [0.5764706 , 0.45882353, 0.21960784, ..., 0.33333334,
         0.2901961 , 0.26666668]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4956_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG945_batch2_brown_ok_3.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.22352941, 0.21960784, 0.0

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.32941177, 0.2627451 , 0.10980392, ..., 0.29411766,
         0.38431373, 0.34509805],
        [0.35686275, 0.3137255 , 0.19607843, ..., 0.43137255,
         0.49411765, 0.4862745 ],
        [0.32156864, 0.28235295, 0.14117648, ..., 0.36078432,
         0.44705883, 0.43137255],
        ...,
        [0.21960784, 0.1764706 , 0.08235294, ..., 0.09019608,
         0.07450981, 0.02745098],
        [0.23529412, 0.19215687, 0.09411765, ..., 0.09019608,
         0.07450981, 0.07450981],
        [0.25490198, 0.21176471, 0.10588235, ..., 0.05882353,
         0.05490196, 0.05490196]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1706_batch2_brown_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4578_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.47843137, 0.48235294, 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6033_batch2_white_ok_1.jpg'b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN5110_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4716_batch2_white_ok_0.jpg'

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.28627452, 0.2627451 , 0.13725491, ..., 0.12941177,
         0.15294118, 0.07058824],
        [0.2784314 , 0.2509804 , 0.07843138, ..., 0.12941177,
         0.17254902, 0.16862746],
        [0.2627451 , 0.22745098, 0.05882353, ..., 0.09019608,
         0.14509805, 0.14509805],
        ...,
        [0.28627452, 0.24705882, 0.09019608, ..., 0.10196079,
         0.09411765, 0.07843138],
        [0.3019608 , 0.2627451 , 0.10196079, ..., 0.14509805,
         0.14901961, 0.12156863],
        [0.36078432, 0.31764707, 0.09411765, ..., 0.1882353 ,
         0.19607843, 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1907_batch2_brown_ok_1.jpg'(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.25490198, 0.23137255, 0.14509805, ..., 0.02352941,
         0.01960784, 0.01960784],
        [0.23137255, 0.21568628, 0.12941177, ..., 0.05882353,
         0.05882353, 0.05882353],
        [0.22745098, 0.21960784, 0.13725491, ..., 0.06666667,
         0.07058824, 0.07058824],
        ...,
        [0.5254902 , 0.4       , 0.09803922, ..., 0.2784314 ,
         0.3137255 , 0.3254902 ],
        [0.4627451 , 0.34117648, 0.09019608, ..., 0.42352942,
         0.42352942, 0.39215687],
        [0.39215687, 0.28235295, 0.06666667, ..., 0.3137255 ,
         0.33333334, 0.26666668]]], dtype=float32)>,)

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4684_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_0202

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN6605_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4913_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG957_batch2_brown_ok_4.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.34901962, 0.29411766, 0.12941177, ..., 0.22352941,
         0.22352941, 0.15294118],
        [0.39215687, 0.34117648, 0.18431373, ..., 0.30588236,
         0.30980393, 0.25490198],
        [0.38039216, 0.3254902 , 0.15686275, ..., 0.23529412,
         0.23921569, 0.19607843],
        ...,
        [0.37254903, 0.34117648, 0.13333334, ..., 0.15686275,
         0.15686275, 0.15686275],
        [0.46666667, 0.45882353, 0.16078432, ..., 0.10196079,
         0.10196079, 0.07058824],
        [0.53333336, 0.5294118 , 0.21960784, ..., 0.03921569,
         0.05098039, 0.0

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4328_batch2_white_ok_0.jpg'(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.59607846, 0.5294118 , 0.2901961 , ..., 0.32941177,
         0.34117648, 0.33333334],
        [0.6901961 , 0.6431373 , 0.42352942, ..., 0.4392157 ,
         0.4862745 , 0.47058824],
        [0.5764706 , 0.53333336, 0.3647059 , ..., 0.36078432,
         0.38431373, 0.39215687],
        ...,
        [0.1882353 , 0.22745098, 0.15686275, ..., 0.03137255,
         0.03529412, 0.01960784],
        [0.20784314, 0.22352941, 0.15686275, ..., 0.03529412,
         0.03921569, 0.03137255],
        [0.20392157, 0.23921569, 0.18039216, ..., 0.07843138,
         0.08235294, 0.05098039]]], dtype=float32)>,)

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.34117648, 0.32156864, 0.15294118, ..., 0.07450981,
         0.06666667, 0.07450981],
        [0.39607844, 0.36078432, 0.20392157, ..., 0.16078432,

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.23137255, 0.22352941, 0.09019608, ..., 0.10980392,
         0.14117648, 0.10196079],
        [0.26666668, 0.23921569, 0.10196079, ..., 0.1254902 ,
         0.16078432, 0.13725491],
        [0.2627451 , 0.23529412, 0.10588235, ..., 0.10588235,
         0.14901961, 0.14509805],
        ...,
        [0.2       , 0.18431373, 0.12941177, ..., 0.3254902 ,
         0.30588236, 0.27058825],
        [0.20392157, 0.18431373, 0.15294118, ..., 0.56078434,
         0.56078434, 0.53333336],
        [0.23137255, 0.21176471, 0.10196079, ..., 0.5411765 ,
         0.5411765 , 0.48235294]]], dtype=float32)>,)b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4610_batch2_white_ok_0.jpg'

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.26666668, 0.22352941, 0.08235294, ..., 0.07843138,
         0.07843138, 0.01960784],
        [0.27450982, 0.22352941, 0.09019608, ..., 0.07843138,

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.25490198, 0.23529412, 0.08235294, ..., 0.14117648,
         0.21568628, 0.21176471],
        [0.2901961 , 0.2784314 , 0.13333334, ..., 0.10980392,
         0.1882353 , 0.16862746],
        [0.27450982, 0.24313726, 0.10196079, ..., 0.08235294,
         0.14901961, 0.13725491],
        ...,
        [1.        , 1.        , 0.99607843, ..., 0.13725491,
         0.15294118, 0.09019608],
        [1.        , 0.99215686, 1.        , ..., 0.12941177,
         0.13333334, 0.08235294],
        [0.84705883, 0.827451  , 0.7490196 , ..., 0.13333334,
         0.10196079, 0.05882353]]], dtype=float32)>,)b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN6793_batch2_white_ok_0.jpg'

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.27450982, 0.23921569, 0.11764706, ..., 0.13333334,
         0.19215687, 0.2       ],
        [0.27450982, 0.23921569, 0.09803922, ..., 0.14901961,

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.27058825, 0.29803923, 0.19215687, ..., 0.10980392,
         0.10980392, 0.10980392],
        [0.2509804 , 0.28627452, 0.1764706 , ..., 0.10196079,
         0.09411765, 0.0627451 ],
        [0.24705882, 0.27450982, 0.16862746, ..., 0.07450981,
         0.07450981, 0.03529412],
        ...,
        [0.3372549 , 0.26666668, 0.18039216, ..., 0.07058824,
         0.06666667, 0.05882353],
        [0.3372549 , 0.26666668, 0.17254902, ..., 0.12156863,
         0.11764706, 0.09803922],
        [0.2509804 , 0.21176471, 0.10980392, ..., 0.09803922,
         0.07843138, 0.05098039]]], dtype=float32)>,)b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6065_batch2_white_ok_2.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS5991_batch2_white_ok_0.jpg'

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.21568628, 0.21568628, 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1727_batch2_brown_ok_0.jpg'b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG448_batch2_brown_ok_0.jpg'

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.27450982, 0.21568628, 0.05098039, ..., 0.05490196,
         0.10196079, 0.09019608],
        [0.25490198, 0.20784314, 0.09411765, ..., 0.09019608,
         0.14509805, 0.09411765],
        [0.2627451 , 0.21568628, 0.12156863, ..., 0.09019608,
         0.14117648, 0.13333334],
        ...,
        [0.49803922, 0.39607844, 0.18431373, ..., 0.69803923,
         0.6745098 , 0.6431373 ],
        [0.44705883, 0.36078432, 0.14901961, ..., 0.9843137 ,
         0.9607843 , 0.9411765 ],
        [0.40392157, 0.3137255 , 0.10980392, ..., 0.8039216 ,
         0.8039216 , 0.8039216 ]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.5372549 , 0.4627451 , 0.34509805, ..., 0.34117648,
         0.3372549 , 0.3019608 ],
        [0.9882353 , 0.9098039 , 0.8       , ..., 0.34509805,
         0.34117648, 0.3254902 ],
        [1.        , 1.        , 0.99607843, ..., 0.22352941,
         0.22745098, 0.22352941],
        ...,
        [0.23529412, 0.1882353 , 0.05490196, ..., 0.09411765,
         0.14509805, 0.12156863],
        [0.23921569, 0.1882353 , 0.05490196, ..., 0.07450981,
         0.14509805, 0.1254902 ],
        [0.17254902, 0.16862746, 0.05882353, ..., 0.05882353,
         0.09411765, 0.08235294]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1174_batch2_brown_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS5970_batch2_white_ok_1.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.27450982, 0.25490198, 0.

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.4745098 , 0.43529412, 0.36862746, ..., 0.19215687,
         0.24313726, 0.21176471],
        [0.5686275 , 0.56078434, 0.5372549 , ..., 0.21568628,
         0.25490198, 0.2509804 ],
        [0.49019608, 0.4745098 , 0.44313726, ..., 0.22745098,
         0.25882354, 0.25490198],
        ...,
        [0.20784314, 0.1764706 , 0.07843138, ..., 0.3372549 ,
         0.15294118, 0.07450981],
        [0.2       , 0.16470589, 0.08235294, ..., 0.15686275,
         0.13333334, 0.10196079],
        [0.16078432, 0.1254902 , 0.04705882, ..., 0.11372549,
         0.10196079, 0.09803922]]], dtype=float32)>,)b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4745_batch2_white_ok_0.jpg'

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.42352942, 0.3372549 , 0.14901961, ..., 0.25490198,
         0.28627452, 0.27058825],
        [0.43529412, 0.36078432, 0.24313726, ..., 0.3254902 ,

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4302_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.3647059 , 0.3647059 , 0.24705882, ..., 0.0627451 ,
         0.05882353, 0.02352941],
        [0.43529412, 0.44705883, 0.32941177, ..., 0.07843138,
         0.07450981, 0.02745098],
        [0.25882354, 0.24313726, 0.13333334, ..., 0.07843138,
         0.07843138, 0.05882353],
        ...,
        [0.07450981, 0.09411765, 0.05490196, ..., 0.07450981,
         0.10588235, 0.10980392],
        [0.10196079, 0.11372549, 0.07058824, ..., 0.08627451,
         0.13725491, 0.12156863],
        [0.10588235, 0.09803922, 0.04313726, ..., 0.09411765,
         0.12941177, 0.08627451]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4918_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.26666668, 0.2627451 , 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS5957_batch2_white_ok_3.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6172_batch2_white_ok_1.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.3529412 , 0.29411766, 0.17254902, ..., 0.13725491,
         0.23137255, 0.22745098],
        [0.42745098, 0.37254903, 0.27450982, ..., 0.1254902 ,
         0.21960784, 0.23529412],
        [0.3529412 , 0.2784314 , 0.16862746, ..., 0.07450981,
         0.1254902 , 0.12941177],
        ...,
        [0.99215686, 0.94509804, 0.7529412 , ..., 0.2901961 ,
         0.16862746, 0.16862746],
        [0.80784315, 0.72156864, 0.47843137, ..., 0.25490198,
         0.14509805, 0.11764706],
        [0.36078432, 0.28235295, 0.10196079, ..., 0.16862746,
         0.1764706 , 0.09803922]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.30588236, 0.25490198, 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN5491_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG907_batch2_brown_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6608_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6189_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.2901961 , 0.23137255, 0.04705882, ..., 0.18039216,
         0.21568628, 0.14509805],
        [0.33333334, 0.28627452, 0.09803922, ..., 0.1882353 ,
         0.23529412, 0.23137255],
        [0.3372549 , 0.28627452, 0.10980392, ..., 0.13725491,
         0.16470589, 0.16862746],
        ...,
        [0.21568628, 0.19215687, 0.07843138, ..., 0.03921569,
         0.03529412, 0.        ],
        [0.22745098, 0.21176471, 0.11372549, ..., 0.03529412

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN5096_batch2_white_ok_1.jpg'b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN5009_batch2_white_ok_0.jpg'

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1436_batch2_brown_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.49019608, 0.4509804 , 0.30588236, ..., 0.37254903,
         0.36862746, 0.32156864],
        [0.6156863 , 0.54509807, 0.44705883, ..., 0.40784314,
         0.40784314, 0.4       ],
        [0.54509807, 0.5058824 , 0.39607844, ..., 0.44313726,
         0.42745098, 0.40784314],
        ...,
        [0.26666668, 0.21176471, 0.09803922, ..., 0.03921569,
         0.07058824, 0.07058824],
        [0.2901961 , 0.21960784, 0.10196079, ..., 0.07058824,
         0.07843138, 0.05490196],
        [0.3137255 , 0.23921569, 0.12156863, ..., 0.11372549,
         0.11372549, 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG384_batch2_brown_ok_2.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.43529412, 0.37254903, 0.24313726, ..., 0.22352941,
         0.25882354, 0.2627451 ],
        [0.5372549 , 0.48235294, 0.36078432, ..., 0.3647059 ,
         0.41960785, 0.38039216],
        [0.54901963, 0.48235294, 0.34901962, ..., 0.30980393,
         0.36078432, 0.34509805],
        ...,
        [0.67058825, 0.5882353 , 0.41568628, ..., 0.05882353,
         0.07450981, 0.05882353],
        [0.4509804 , 0.36862746, 0.21960784, ..., 0.07843138,
         0.07843138, 0.05098039],
        [0.31764707, 0.23529412, 0.08627451, ..., 0.05098039,
         0.07058824, 0.05098039]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6649_batch2_white_ok_1.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1110_batch2_brown_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6348_batch2_white_ok_1.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1218_batch2_brown_ok_2.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.3882353 , 0.30980393, 0.1764706 , ..., 0.09019608,
         0.09019608, 0.03137255],
        [0.32941177, 0.25882354, 0.12156863, ..., 0.07450981,
         0.08235294, 0.01960784],
        [0.30588236, 0.22352941, 0.08627451, ..., 0.08627451,
         0.09019608, 0.03921569],
        ...,
        [0.76862746, 0.6627451 , 0.40784314, ..., 0.1882353 ,
         0.18431373, 0.14901961],
        [0.6509804 , 0.5647059 , 0.37254903, ..., 0.16078432,
         0.13725491, 0.11764706],
        [0.5019608 , 0.40392157, 0.16862746, ..., 0.07058824,
         0.07058824, 0.

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.27450982, 0.19215687, 0.05882353, ..., 0.05098039,
         0.10980392, 0.10588235],
        [0.27450982, 0.2       , 0.07843138, ..., 0.09411765,
         0.15686275, 0.12941177],
        [0.2627451 , 0.18431373, 0.06666667, ..., 0.11372549,
         0.14901961, 0.14509805],
        ...,
        [0.46666667, 0.47058824, 0.16078432, ..., 0.34901962,
         0.4627451 , 0.39215687],
        [0.45490196, 0.40784314, 0.11372549, ..., 0.47058824,
         0.48235294, 0.3372549 ],
        [0.43529412, 0.39607844, 0.12156863, ..., 0.45882353,
         0.4392157 , 0.26666668]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4501_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.29411766, 0.22745098, 0.07450981, ..., 0.15686275,
         0.21568628, 0.21568628],
        [0.3137255 , 0.25490198, 0.09803922, ..., 0.1882353 ,

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1643_batch2_brown_ok_0.jpg'b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN5085_batch2_white_ok_0.jpg'

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG338_batch2_brown_ok_1.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.2509804 , 0.24705882, 0.13725491, ..., 0.07058824,
         0.12156863, 0.1254902 ],
        [0.27058825, 0.27058825, 0.13725491, ..., 0.10980392,
         0.16470589, 0.11372549],
        [0.25490198, 0.21568628, 0.08235294, ..., 0.07843138,
         0.13725491, 0.11764706],
        ...,
        [0.28627452, 0.23137255, 0.10588235, ..., 0.5686275 ,
         0.5647059 , 0.56078434],
        [0.27450982, 0.22352941, 0.10980392, ..., 0.40392157,
         0.40784314, 0.39607844],
        [0.2509804 , 0.20392157, 0.11372549, ..., 0.18039216,
         0.18039216, 0.1

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG464_batch2_brown_ok_1.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6052_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN6165_batch2_white_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.24705882, 0.22352941, 0.08235294, ..., 0.34901962,
         0.34117648, 0.32156864],
        [0.25490198, 0.24313726, 0.14901961, ..., 0.4627451 ,
         0.48235294, 0.45882353],
        [0.2627451 , 0.22745098, 0.09803922, ..., 0.40392157,
         0.43529412, 0.42745098],
        ...,
        [0.15294118, 0.16862746, 0.20392157, ..., 0.1764706 ,
         0.18039216, 0.12156863],
        [0.03921569, 0.05490196, 0.06666667, ..., 0.2       ,
         0.19215687, 0.09411765],
        [0.05882353, 0.05882353, 0.05490196, ..., 0.1254902 ,
         0.10588235, 0.0

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.24313726, 0.2784314 , 0.19215687, ..., 0.08235294,
         0.07450981, 0.01960784],
        [0.20392157, 0.23921569, 0.15294118, ..., 0.10196079,
         0.09411765, 0.02352941],
        [0.2       , 0.22745098, 0.12156863, ..., 0.09411765,
         0.09803922, 0.05490196],
        ...,
        [0.43529412, 0.39215687, 0.30588236, ..., 0.15686275,
         0.15686275, 0.14901961],
        [0.60784316, 0.5647059 , 0.4627451 , ..., 0.19215687,
         0.23921569, 0.23137255],
        [0.5019608 , 0.45490196, 0.4       , ..., 0.1882353 ,
         0.20784314, 0.22745098]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1155_batch2_brown_ok_1.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.2627451 , 0.22352941, 0.11764706, ..., 0.08627451,
         0.15686275, 0.14901961],
        [0.25882354, 0.24705882, 0.16470589, ..., 0.08627451,

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6588_batch2_white_ok_2.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.39607844, 0.34117648, 0.21568628, ..., 0.2784314 ,
         0.30980393, 0.27058825],
        [0.47058824, 0.41568628, 0.2901961 , ..., 0.3529412 ,
         0.41960785, 0.34901962],
        [0.50980395, 0.4627451 , 0.32941177, ..., 0.27058825,
         0.2901961 , 0.2784314 ],
        ...,
        [0.27058825, 0.21960784, 0.09411765, ..., 0.07843138,
         0.05882353, 0.03921569],
        [0.2901961 , 0.21960784, 0.10196079, ..., 0.07450981,
         0.05098039, 0.02352941],
        [0.3137255 , 0.23921569, 0.12156863, ..., 0.06666667,
         0.04313726, 0.03137255]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.28235295, 0.21960784, 0.09019608, ..., 0.05490196,
         0.05490196, 0.01960784],
        [0.2784314 , 0.20392157, 0.07450981, ..., 0.09019608,

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.24705882, 0.20392157, 0.06666667, ..., 0.01960784,
         0.01960784, 0.01960784],
        [0.25490198, 0.20392157, 0.07058824, ..., 0.03921569,
         0.04313726, 0.03921569],
        [0.25490198, 0.21176471, 0.07058824, ..., 0.04705882,
         0.0627451 , 0.03529412],
        ...,
        [0.38431373, 0.3254902 , 0.2       , ..., 0.28235295,
         0.25490198, 0.14901961],
        [0.44705883, 0.39215687, 0.2627451 , ..., 0.36862746,
         0.34509805, 0.32156864],
        [0.45490196, 0.39607844, 0.23137255, ..., 0.29411766,
         0.28235295, 0.28235295]]], dtype=float32)>,)b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6310_batch2_white_ok_1.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1529_batch2_brown_ok_3.jpg'

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.3254902 , 0.30980393, 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG1547_batch2_brown_ok_1.jpg'b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG888_batch2_brown_ok_4.jpg'

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN4853_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN5018_batch2_white_ok_0.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG794_batch2_brown_ok_1.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.3137255 , 0.2627451 , 0.13725491, ..., 0.04313726,
         0.03921569, 0.03921569],
        [0.27058825, 0.21960784, 0.09411765, ..., 0.07450981,
         0.07450981, 0.07843138],
        [0.2509804 , 0.20784314, 0.07843138, ..., 0.07450981,
         0.07843138, 0.07058824],
        ...,
        [0.41960785, 0.34901962, 0.

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG428_batch2_brown_ok_2.jpg'b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG155_batch2_brown_ok_0.jpg'
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.27058825, 0.24705882, 0.07450981, ..., 0.14509805,
         0.2       , 0.13725491],
        [0.30980393, 0.2784314 , 0.11764706, ..., 0.21176471,
         0.26666668, 0.21568628],
        [0.29411766, 0.2509804 , 0.09803922, ..., 0.1254902 ,
         0.1882353 , 0.1764706 ],
        ...,
        [0.27450982, 0.31764707, 0.24705882, ..., 0.05098039,
         0.04705882, 0.02745098],
        [0.39607844, 0.42352942, 0.32156864, ..., 0.01960784,
         0.01568628, 0.00392157],
        [0.27058825, 0.30588236, 0.2       , ..., 0.        ,
         0.        , 0.        ]]], dtype=float32)>,)
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SN

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SS6394_batch2_white_ok_0.jpg'(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.3137255 , 0.2784314 , 0.15686275, ..., 0.09803922,
         0.13333334, 0.1254902 ],
        [0.27450982, 0.23921569, 0.10588235, ..., 0.07843138,
         0.10980392, 0.10980392],
        [0.27450982, 0.23921569, 0.09411765, ..., 0.07843138,
         0.10196079, 0.09411765],
        ...,
        [0.654902  , 0.56078434, 0.3764706 , ..., 0.43137255,
         0.3882353 , 0.3647059 ],
        [0.7019608 , 0.63529414, 0.4627451 , ..., 0.4117647 ,
         0.44705883, 0.44705883],
        [0.60784316, 0.5137255 , 0.40392157, ..., 0.28627452,
         0.33333334, 0.32941177]]], dtype=float32)>,)

b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023SG756_batch2_brown_ok_3.jpg'
b'I:\\download\\deepLearning\\datasets\\keelYolo\\keelTwoCalssesDataset\\images\\edged_02023

(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.2509804 , 0.23137255, 0.07843138, ..., 0.22745098,
         0.27450982, 0.22352941],
        [0.3019608 , 0.2627451 , 0.09803922, ..., 0.22745098,
         0.2901961 , 0.25882354],
        [0.2901961 , 0.25490198, 0.09411765, ..., 0.24313726,
         0.28627452, 0.2627451 ],
        ...,
        [0.43137255, 0.41568628, 0.19607843, ..., 0.11372549,
         0.07843138, 0.03921569],
        [0.4392157 , 0.43529412, 0.22745098, ..., 0.16862746,
         0.11764706, 0.06666667],
        [0.47843137, 0.46666667, 0.23529412, ..., 0.22352941,
         0.1882353 , 0.11764706]]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 912, 912), dtype=float32, numpy=
array([[[0.2       , 0.20392157, 0.05882353, ..., 0.10196079,
         0.14509805, 0.09803922],
        [0.2       , 0.2       , 0.05098039, ..., 0.16078432,
         0.20392157, 0.14117648],
        [0.2       , 0.18431373, 0.04705882, ..., 0.10588235,
         0.14117648, 0.07

In [87]:
def image_normalization(img, img_min=0, img_max=255):
    """This is a typical image normalization function
    where the minimum and maximum of the image is needed
    source: https://en.wikipedia.org/wiki/Normalization_(image_processing)
    :param img: an image could be gray scale or color
    :param img_min:  for default is 0
    :param img_max: for default is 255
    :return: a normalized image, if max is 255 the dtype is uint8
    """
    img = np.float32(img)
    epsilon=1e-12 # whenever an inconsistent image
    img = (img-np.min(img))*(img_max-img_min)/((np.max(img)-np.min(img))+epsilon)+img_min
    return img

In [100]:

n=0
#for z in dataset_:
   # n=n+1
input_path = os.path.join(workPath, "edged_02023SG3_batch2_brown_ok_0.jpg")
image = cv2.imread(input_path, cv2.IMREAD_GRAYSCALE)

image = image/255.0 # normalization
image = image.astype(np.float32)
image = cv2.resize(image, (912,912))
image = np.expand_dims(image, axis=-1)
#plt.imshow(image)

res_pre = model.predict(image)
#res = res_pre[-1,:,:]
res *= 255.0
plt.imshow(res)
    #fullpath = os.path.join(outPath, 'masked_'+str(n))
    #cv2.imwrite(fullpath, res_pre)


InvalidArgumentError: Graph execution error:

transpose expects a vector of size 3. But input(1) is a vector of size 4
	 [[{{node model/conv2d/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer}}]] [Op:__inference_predict_function_41526]