In [1]:
import tensorflow as tf
import pathlib
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

np.set_printoptions(precision=4)

2024-11-10 15:00:13.066276: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9373] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-10 15:00:13.066435: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-10 15:00:13.196383: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1534] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [2]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
dataset

2024-11-10 15:02:48.883842: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:00:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-11-10 15:02:49.187253: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:00:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-11-10 15:02:49.187546: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:00:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-11-10 15:02:49.190569: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:00:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-11-10 15:02:49.190743: I external/local_xla/xla/stream_executor

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [3]:
for elem in dataset:
  print(elem.numpy())

8
3
0
8
2
1


In [4]:
it = iter(dataset)

print(next(it).numpy())

8


In [5]:
dataset.element_spec

TensorSpec(shape=(), dtype=tf.int32, name=None)

In [6]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(100,), dtype=tf.int32, name=None))

In [8]:
dataset3 = tf.data.Dataset.zip((dataset, dataset2))

dataset3.element_spec

(TensorSpec(shape=(), dtype=tf.int32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(100,), dtype=tf.int32, name=None)))

In [10]:
dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4]))

dataset4.element_spec

SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [12]:
dataset4.element_spec.value_type

tensorflow.python.framework.sparse_tensor.SparseTensor

In [18]:
dataset1 = tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4, 10], minval=1, maxval=10, dtype=tf.int32))

for z in dataset1:
  print(z.numpy())

[7 5 4 5 8 5 7 3 8 7]
[1 7 1 3 5 8 6 8 2 7]
[2 3 1 8 9 5 1 1 9 6]
[6 3 8 2 9 3 6 1 5 2]


In [20]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))

for z in dataset2:
  print(z)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.23188627>, <tf.Tensor: shape=(100,), dtype=int32, numpy=
array([24, 76, 56, 13, 90, 21, 31, 29, 16, 54, 72, 11, 13, 74, 75, 85, 93,
       38, 92, 42, 69, 81, 71, 66, 52, 98, 10, 26, 33, 45,  3, 87, 83, 41,
       91, 58, 20, 66, 38, 87, 70, 51, 53,  2,  4, 78, 26, 89, 52, 25, 37,
       53, 39, 42, 76, 34, 18, 29, 56,  8, 83, 15, 52, 56, 31, 86,  4, 46,
       82, 11, 67, 73,  9, 25, 20, 13, 12, 25, 88, 75, 53, 50, 53, 38, 85,
       84, 89, 52, 12,  3, 63, 22, 32,  0, 53, 32, 81, 68,  6, 47],
      dtype=int32)>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.20562696>, <tf.Tensor: shape=(100,), dtype=int32, numpy=
array([23, 40, 26, 10, 34, 72, 68, 32, 74, 10, 77, 52, 59, 37,  8, 21, 16,
       61, 14, 64, 99,  3, 10, 32, 17, 22, 18, 78, 87, 62, 16, 50, 73, 91,
       55, 94, 53, 39, 55, 15, 56, 52, 33, 13, 48, 84, 50, 59, 40, 79, 36,
       66, 78, 68, 54, 73, 19, 42, 94, 91, 49, 47, 14, 85, 60, 74, 41, 59,
       74, 47, 43, 33, 69, 58,

In [22]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

for a, (b,c) in dataset3:
  print('shapes: {a.shape}, {b.shape}, {c.shape}'.format(a=a, b=b, c=c))

shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)


In [34]:
def count(stop):
  i = 0
  while i<stop:
    yield i
    i += 1

      
for n in count(5):
  print(n)

0
1
2
3
4


In [49]:
ds_counter = tf.data.Dataset.from_generator(count, args=[25], output_types=tf.int32, output_shapes = (), )
for count_batch in ds_counter.repeat().batch(6).take(1):
  print(count_batch.numpy())

[0 1 2 3 4 5]


In [44]:
def gen_series():
  i = 0
  while True:
    size = np.random.randint(0, 10)
    yield i, np.random.normal(size=(size,))
    i += 1
for i, series in gen_series():
  print(i, ":", str(series))
  if i > 5:
    break

      

0 : [-0.9718 -0.2935]
1 : [-0.7655 -0.4276 -0.5032]
2 : [-0.3409]
3 : [ 1.4888 -0.0656  1.054   3.0871 -0.9626]
4 : [-1.8391 -0.7658 -1.5449 -1.0887 -0.7001  0.6878 -0.1837]
5 : []
6 : [0.4934]


In [45]:
ds_series = tf.data.Dataset.from_generator(
    gen_series,
    output_types=(tf.int32, tf.float32),
    output_shapes=((), (None,)))

ds_series

<_FlatMapDataset element_spec=(TensorSpec(shape=(), dtype=tf.int32, name=None), TensorSpec(shape=(None,), dtype=tf.float32, name=None))>

In [46]:
ds_series_batch = ds_series.shuffle(20).padded_batch(10)

ids, sequence_batch = next(iter(ds_series_batch))
print(ids.numpy())
print()
print(sequence_batch.numpy())

[ 5 10  9  0  4 15 11 13 26 22]

[[-0.3957  0.6878 -1.1684 -0.5284  2.2756  1.062   0.22    0.      0.    ]
 [ 1.2938  0.      0.      0.      0.      0.      0.      0.      0.    ]
 [-0.0681  1.2538  2.4857  0.4479  1.2044  0.      0.      0.      0.    ]
 [-0.4797  0.6935 -1.5512  1.7128 -0.1282 -0.4189 -0.2981  0.5774 -0.066 ]
 [ 0.4854  0.148   0.3847  0.0089  0.      0.      0.      0.      0.    ]
 [-0.6327  0.197   0.      0.      0.      0.      0.      0.      0.    ]
 [ 0.658  -0.6767 -0.1423  0.698  -0.5115  0.3881  0.      0.      0.    ]
 [ 0.      0.      0.      0.      0.      0.      0.      0.      0.    ]
 [-1.0399  1.2333  0.3618 -0.2724 -0.4229  1.4129  0.2917  0.      0.    ]
 [-0.0453  0.9444  0.3783  0.367   0.5489  0.8278  1.0721  0.1808  0.    ]]
